function DrawRedCross( self )

Screen('DrawLine', self.wPtr , [255 0 0 255], ...
    self.low_reward.currRect(1), ...
    self.low_reward.currRect(2), ...
    self.low_reward.currRect(3), ...
    self.low_reward.currRect(4), ...
    10);

Screen('DrawLine', self.wPtr , [255 0 0 255], ...
    self.low_reward.currRect(1), ...
    self.low_reward.currRect(4), ...
    self.low_reward.currRect(3), ...
    self.low_reward.currRect(2), ...
    10);

end
