function [ instruction ] = Instruction( FIXATION )
global S

instruction = Instruction( ...
    FIXATION,...
    S.Parameters.Forte.Instruction.color,...
    S.Parameters.Forte.Instruction.diameter_ratio,...
    S.Parameters.Forte.Instruction.thickness_ratio...
    );

instruction.AssertReady % just to check

end % function